[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-gen = "0.3.1"
borsh = "1.5.3"
bs58 = "0.5.1"
solana-client = "1.16.0"
solana-program = "1.16.0"
solana-sdk = "1.15.2"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
